// Sample server data
// In a real application, this would come from an API

export const servers = [
  // Free Servers
  {
    id: 1,
    country: 'United States',
    flag: '🇺🇸',
    region: 'North America',
    city: 'New York',
    ping: 85,
    load: 65,
    bandwidth: '500 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256',
    status: 'online',
    isPremium: false,
  },
  {
    id: 2,
    country: 'Germany',
    flag: '🇩🇪',
    region: 'Europe',
    city: 'Frankfurt',
    ping: 110,
    load: 45,
    bandwidth: '750 Mbps',
    protocol: 'TCP',
    encryption: 'AES-256',
    status: 'online',
    isPremium: false,
  },
  {
    id: 3,
    country: 'Singapore',
    flag: '🇸🇬',
    region: 'Asia',
    city: 'Singapore',
    ping: 150,
    load: 70,
    bandwidth: '500 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256',
    status: 'online',
    isPremium: false,
  },
  {
    id: 4,
    country: 'Netherlands',
    flag: '🇳🇱',
    region: 'Europe',
    city: 'Amsterdam',
    ping: 95,
    load: 55,
    bandwidth: '750 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256',
    status: 'online',
    isPremium: false,
  },
  {
    id: 5,
    country: 'Canada',
    flag: '🇨🇦',
    region: 'North America',
    city: 'Toronto',
    ping: 90,
    load: 60,
    bandwidth: '600 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256',
    status: 'online',
    isPremium: false,
  },
  {
    id: 22,
    country: 'Mexico',
    flag: '🇲🇽',
    region: 'North America',
    city: 'Mexico City',
    ping: 115,
    load: 40,
    bandwidth: '450 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256',
    status: 'online',
    isPremium: false,
  },
  {
    id: 23,
    country: 'India',
    flag: '🇮🇳',
    region: 'Asia',
    city: 'Mumbai',
    ping: 180,
    load: 85,
    bandwidth: '350 Mbps',
    protocol: 'TCP',
    encryption: 'AES-256',
    status: 'online',
    isPremium: false,
  },
  {
    id: 24,
    country: 'South Africa',
    flag: '🇿🇦',
    region: 'Africa',
    city: 'Johannesburg',
    ping: 230,
    load: 35,
    bandwidth: '300 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256',
    status: 'online',
    isPremium: false,
  },
  
  // Premium Servers
  {
    id: 6,
    country: 'United Kingdom',
    flag: '🇬🇧',
    region: 'Europe',
    city: 'London',
    ping: 80,
    load: 30,
    bandwidth: '1 Gbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 7,
    country: 'Japan',
    flag: '🇯🇵',
    region: 'Asia',
    city: 'Tokyo',
    ping: 160,
    load: 25,
    bandwidth: '1 Gbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 8,
    country: 'Australia',
    flag: '🇦🇺',
    region: 'Oceania',
    city: 'Sydney',
    ping: 210,
    load: 35,
    bandwidth: '900 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 9,
    country: 'France',
    flag: '🇫🇷',
    region: 'Europe',
    city: 'Paris',
    ping: 90,
    load: 40,
    bandwidth: '1 Gbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 10,
    country: 'Switzerland',
    flag: '🇨🇭',
    region: 'Europe',
    city: 'Zurich',
    ping: 85,
    load: 25,
    bandwidth: '1 Gbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 11,
    country: 'Hong Kong',
    flag: '🇭🇰',
    region: 'Asia',
    city: 'Hong Kong',
    ping: 145,
    load: 50,
    bandwidth: '900 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 12,
    country: 'Sweden',
    flag: '🇸🇪',
    region: 'Europe',
    city: 'Stockholm',
    ping: 100,
    load: 30,
    bandwidth: '1 Gbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 13,
    country: 'Italy',
    flag: '🇮🇹',
    region: 'Europe',
    city: 'Milan',
    ping: 115,
    load: 45,
    bandwidth: '900 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 14,
    country: 'South Korea',
    flag: '🇰🇷',
    region: 'Asia',
    city: 'Seoul',
    ping: 170,
    load: 35,
    bandwidth: '900 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 15,
    country: 'Brazil',
    flag: '🇧🇷',
    region: 'South America',
    city: 'Sao Paulo',
    ping: 190,
    load: 40,
    bandwidth: '800 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 16,
    country: 'United States',
    flag: '🇺🇸',
    region: 'North America',
    city: 'Los Angeles',
    ping: 95,
    load: 35,
    bandwidth: '1 Gbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 17,
    country: 'Spain',
    flag: '🇪🇸',
    region: 'Europe',
    city: 'Madrid',
    ping: 105,
    load: 30,
    bandwidth: '1 Gbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 18,
    country: 'United Arab Emirates',
    flag: '🇦🇪',
    region: 'Middle East',
    city: 'Dubai',
    ping: 150,
    load: 20,
    bandwidth: '900 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 19,
    country: 'New Zealand',
    flag: '🇳🇿',
    region: 'Oceania',
    city: 'Auckland',
    ping: 220,
    load: 15,
    bandwidth: '850 Mbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 20,
    country: 'Norway',
    flag: '🇳🇴',
    region: 'Europe',
    city: 'Oslo',
    ping: 110,
    load: 25,
    bandwidth: '1 Gbps',
    protocol: 'UDP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
  {
    id: 21,
    country: 'Russia',
    flag: '🇷🇺',
    region: 'Europe/Asia',
    city: 'Moscow',
    ping: 140,
    load: 60,
    bandwidth: '800 Mbps',
    protocol: 'TCP',
    encryption: 'AES-256-GCM',
    status: 'online',
    isPremium: true,
  },
];

/**
 * IMPLEMENTATION GUIDE:
 * 
 * In a real VPN application, you would fetch server information from your backend:
 * 
 * 1. Create an API endpoint that provides:
 *    - Server locations
 *    - Current server load/status
 *    - Ping/latency information
 *    - Premium/free status
 * 
 * 2. Implement proper authentication for accessing premium servers
 * 
 * 3. Include detailed server configuration for VPN protocols:
 *    - Server hostnames/IPs
 *    - Ports and protocols (UDP/TCP)
 *    - Encryption settings
 *    - Certificate paths or inline certificates
 * 
 * 4. Consider caching server data for offline access
 * 
 * 5. Implement server status checks and automatic selection
 *    of the best server based on latency
 */
